"""add_field_definitions_card_fields_time_entries

Revision ID: 33463cd89062
Revises: 559b1add1bea
Create Date: 2026-06-13 09:20:26.430825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '33463cd89062'
down_revision: Union[str, Sequence[str], None] = '559b1add1bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_definitions',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('board_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_definitions_board_id'), 'field_definitions', ['board_id'], unique=False)
    op.create_table('card_fields',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('card_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('field_definition_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['field_definition_id'], ['field_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'field_definition_id', name='uq_card_field')
    )
    op.create_index(op.f('ix_card_fields_card_id'), 'card_fields', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_fields_field_definition_id'), 'card_fields', ['field_definition_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('card_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_entries_card_id'), 'time_entries', ['card_id'], unique=False)
    op.create_index(op.f('ix_time_entries_user_id'), 'time_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_entries_user_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_card_id'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_card_fields_field_definition_id'), table_name='card_fields')
    op.drop_index(op.f('ix_card_fields_card_id'), table_name='card_fields')
    op.drop_table('card_fields')
    op.drop_index(op.f('ix_field_definitions_board_id'), table_name='field_definitions')
    op.drop_table('field_definitions')
    # ### end Alembic commands ###
