"""phase16a_plan_new_columns

Revision ID: 3427c405f3ce
Revises: e5f6a7b8c9d0
Create Date: 2026-06-14 14:26:37.620604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3427c405f3ce'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'slug',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.add_column('plans', sa.Column('sort_order', sa.SmallInteger(), nullable=False))
    op.add_column('plans', sa.Column('is_highlighted', sa.Boolean(), nullable=False))
    op.add_column('plans', sa.Column('stripe_price_id_monthly', sa.String(length=255), nullable=True))
    op.add_column('plans', sa.Column('stripe_price_id_yearly', sa.String(length=255), nullable=True))
    op.add_column('plans', sa.Column('razorpay_plan_id_monthly', sa.String(length=255), nullable=True))
    op.add_column('plans', sa.Column('razorpay_plan_id_yearly', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'razorpay_plan_id_yearly')
    op.drop_column('plans', 'razorpay_plan_id_monthly')
    op.drop_column('plans', 'stripe_price_id_yearly')
    op.drop_column('plans', 'stripe_price_id_monthly')
    op.drop_column('plans', 'is_highlighted')
    op.drop_column('plans', 'sort_order')
    op.alter_column('boards', 'slug',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    # ### end Alembic commands ###
