"""add_phase9_tables

Revision ID: 54de78e271a0
Revises: 7dc4dfaca9a3
Create Date: 2026-06-12 22:44:38.959082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '54de78e271a0'
down_revision: Union[str, Sequence[str], None] = '7dc4dfaca9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notification_prefs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('in_app_mention', sa.Boolean(), nullable=False),
    sa.Column('in_app_comment', sa.Boolean(), nullable=False),
    sa.Column('in_app_reply', sa.Boolean(), nullable=False),
    sa.Column('in_app_card_assigned', sa.Boolean(), nullable=False),
    sa.Column('in_app_join_request', sa.Boolean(), nullable=False),
    sa.Column('email_mention', sa.Boolean(), nullable=False),
    sa.Column('email_comment', sa.Boolean(), nullable=False),
    sa.Column('email_reply', sa.Boolean(), nullable=False),
    sa.Column('email_card_assigned', sa.Boolean(), nullable=False),
    sa.Column('email_card_overdue', sa.Boolean(), nullable=False),
    sa.Column('email_join_request', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_notif_prefs_user')
    )
    op.create_index(op.f('ix_user_notification_prefs_user_id'), 'user_notification_prefs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_notification_prefs_user_id'), table_name='user_notification_prefs')
    op.drop_table('user_notification_prefs')
    # ### end Alembic commands ###
