"""add_phase14_15_tables

Revision ID: 559b1add1bea
Revises: a2db6705d7c1
Create Date: 2026-06-13 09:13:18.978583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '559b1add1bea'
down_revision: Union[str, Sequence[str], None] = 'a2db6705d7c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest_preferences',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('frequency', sa.Enum('off', 'daily', 'weekly', name='digestfrequency'), nullable=False),
    sa.Column('send_hour', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digest_preferences_user_id'), 'digest_preferences', ['user_id'], unique=True)
    op.create_table('card_templates',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('board_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severity'), nullable=True),
    sa.Column('priority', sa.Enum('urgent', 'high', 'normal', 'low', name='priority'), nullable=False),
    sa.Column('checklist_json', sa.Text(), nullable=True),
    sa.Column('created_by_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_templates_board_id'), 'card_templates', ['board_id'], unique=False)
    op.create_table('sla_rules',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('board_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severitylevel'), nullable=False),
    sa.Column('hours_to_resolve', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'severity', name='uq_sla_board_severity')
    )
    op.create_index(op.f('ix_sla_rules_board_id'), 'sla_rules', ['board_id'], unique=False)
    op.create_table('card_watchers',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('card_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'user_id', name='uq_card_watcher')
    )
    op.create_index(op.f('ix_card_watchers_card_id'), 'card_watchers', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_watchers_user_id'), 'card_watchers', ['user_id'], unique=False)
    op.create_foreign_key(None, 'plan_feature_flags', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan_feature_flags', type_='foreignkey')
    op.drop_index(op.f('ix_card_watchers_user_id'), table_name='card_watchers')
    op.drop_index(op.f('ix_card_watchers_card_id'), table_name='card_watchers')
    op.drop_table('card_watchers')
    op.drop_index(op.f('ix_sla_rules_board_id'), table_name='sla_rules')
    op.drop_table('sla_rules')
    op.drop_index(op.f('ix_card_templates_board_id'), table_name='card_templates')
    op.drop_table('card_templates')
    op.drop_index(op.f('ix_digest_preferences_user_id'), table_name='digest_preferences')
    op.drop_table('digest_preferences')
    # ### end Alembic commands ###
