"""phase0_plan_2fa_system_config

Revision ID: 7aa8808f412f
Revises: b6cf68269c32
Create Date: 2026-06-13 02:12:02.107852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7aa8808f412f'
down_revision: Union[str, Sequence[str], None] = 'b6cf68269c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_table('plan_feature_flags',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('plan_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('limit_value', mysql.BIGINT(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_feature_flags_plan_id'), 'plan_feature_flags', ['plan_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_audit_logs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('admin_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_admin_id'), 'admin_audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_performed_at'), 'admin_audit_logs', ['performed_at'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('updated_by_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_config_key'), 'system_configs', ['config_key'], unique=True)
    op.add_column('cards', sa.Column('is_recurring', sa.Boolean(), nullable=False))
    op.add_column('cards', sa.Column('recurrence_pattern', sa.String(length=20), nullable=True))
    op.add_column('cards', sa.Column('recurrence_end_date', sa.DateTime(), nullable=True))
    op.add_column('cards', sa.Column('next_recurrence_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_otp_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_otp_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email_otp_attempts', sa.SmallInteger(), nullable=False))
    op.add_column('users', sa.Column('totp_secret_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('two_fa_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('backup_codes_hash', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('plan_id', mysql.BIGINT(unsigned=True), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'users', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'plan_id')
    op.drop_column('users', 'backup_codes_hash')
    op.drop_column('users', 'two_fa_enabled')
    op.drop_column('users', 'totp_secret_encrypted')
    op.drop_column('users', 'email_otp_attempts')
    op.drop_column('users', 'email_otp_expires_at')
    op.drop_column('users', 'email_otp_hash')
    op.drop_column('users', 'is_verified')
    op.drop_column('cards', 'next_recurrence_at')
    op.drop_column('cards', 'recurrence_end_date')
    op.drop_column('cards', 'recurrence_pattern')
    op.drop_column('cards', 'is_recurring')
    op.drop_index(op.f('ix_system_configs_config_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_admin_audit_logs_performed_at'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_id'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_table('plans')
    op.drop_index(op.f('ix_plan_feature_flags_plan_id'), table_name='plan_feature_flags')
    op.drop_table('plan_feature_flags')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
