"""phase16c_webhook_event_add_fields

Revision ID: 9aabba325589
Revises: d066b15cc21a
Create Date: 2026-06-14 14:54:31.409305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9aabba325589'
down_revision: Union[str, Sequence[str], None] = 'd066b15cc21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('payload_json', sa.Text(), nullable=True))
    op.add_column('webhook_events', sa.Column('processed', sa.Boolean(), nullable=False))
    op.add_column('webhook_events', sa.Column('error', sa.Text(), nullable=True))
    op.drop_column('webhook_events', 'payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('payload', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_column('webhook_events', 'error')
    op.drop_column('webhook_events', 'processed')
    op.drop_column('webhook_events', 'payload_json')
    # ### end Alembic commands ###
