"""add current_refresh_jti to users

Revision ID: a2db6705d7c1
Revises: 7df34c31f8ec
Create Date: 2026-06-13 08:11:11.524803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2db6705d7c1'
down_revision: Union[str, Sequence[str], None] = '7df34c31f8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_refresh_jti', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_refresh_jti')
    # ### end Alembic commands ###
