"""add_coupon_offer_id_and_pending_coupon

Revision ID: a35c45fe9fd2
Revises: e4bb042ac19a
Create Date: 2026-06-15 01:50:29.488480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35c45fe9fd2'
down_revision: Union[str, Sequence[str], None] = 'e4bb042ac19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('razorpay_offer_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('pending_coupon_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'pending_coupon_code')
    op.drop_column('coupons', 'razorpay_offer_id')
    # ### end Alembic commands ###
