"""add integrations and external_refs

Revision ID: b6cf68269c32
Revises: 54de78e271a0
Create Date: 2026-06-12 23:14:27.885248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6cf68269c32'
down_revision: Union[str, Sequence[str], None] = '54de78e271a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('board_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('type', sa.Enum('clickup', 'github', 'gitlab', name='integrationtype'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_board_id'), 'integrations', ['board_id'], unique=False)
    op.create_index(op.f('ix_integrations_created_by_id'), 'integrations', ['created_by_id'], unique=False)
    op.create_table('external_refs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('card_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('integration_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='pushstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('pushed_by_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.ForeignKeyConstraint(['pushed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'integration_id', name='uq_card_integration')
    )
    op.create_index(op.f('ix_external_refs_card_id'), 'external_refs', ['card_id'], unique=False)
    op.create_index(op.f('ix_external_refs_integration_id'), 'external_refs', ['integration_id'], unique=False)
    op.create_index(op.f('ix_external_refs_pushed_by_id'), 'external_refs', ['pushed_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_refs_pushed_by_id'), table_name='external_refs')
    op.drop_index(op.f('ix_external_refs_integration_id'), table_name='external_refs')
    op.drop_index(op.f('ix_external_refs_card_id'), table_name='external_refs')
    op.drop_table('external_refs')
    op.drop_index(op.f('ix_integrations_created_by_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_board_id'), table_name='integrations')
    op.drop_table('integrations')
    # ### end Alembic commands ###
