"""add_pending_upgrade_plan_id_to_subscriptions

Revision ID: c3f3f5209721
Revises: 14555396ba98
Create Date: 2026-06-15 02:24:54.276955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c3f3f5209721'
down_revision: Union[str, Sequence[str], None] = '14555396ba98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('pending_upgrade_plan_id', mysql.BIGINT(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'plans', ['pending_upgrade_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'pending_upgrade_plan_id')
    # ### end Alembic commands ###
