"""phase16a_user_subscription_id

Revision ID: d066b15cc21a
Revises: ed50b7146b4b
Create Date: 2026-06-14 14:34:19.876025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd066b15cc21a'
down_revision: Union[str, Sequence[str], None] = 'ed50b7146b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_id', mysql.BIGINT(unsigned=True), nullable=True))
    op.add_column('users', sa.Column('storage_used_bytes', mysql.BIGINT(unsigned=True), nullable=False))
    op.create_index(op.f('ix_users_subscription_id'), 'users', ['subscription_id'], unique=False)
    op.drop_constraint(op.f('users_ibfk_1'), 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_subscription_id', 'users', 'subscriptions', ['subscription_id'], ['id'], use_alter=True)
    op.drop_column('users', 'plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True))
    op.drop_constraint('fk_users_subscription_id', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_ibfk_1'), 'users', 'plans', ['plan_id'], ['id'])
    op.drop_index(op.f('ix_users_subscription_id'), table_name='users')
    op.drop_column('users', 'storage_used_bytes')
    op.drop_column('users', 'subscription_id')
    # ### end Alembic commands ###
