"""add_billing_cycle_to_subscriptions

Revision ID: e4bb042ac19a
Revises: ff07f20cffc5
Create Date: 2026-06-15 01:19:08.515832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4bb042ac19a'
down_revision: Union[str, Sequence[str], None] = 'ff07f20cffc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('billing_cycle', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'billing_cycle')
    # ### end Alembic commands ###
