"""add_cards_labels_tables

Revision ID: ea15f1cd9122
Revises: 9726c85cad42
Create Date: 2026-06-12 21:57:17.487149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea15f1cd9122'
down_revision: Union[str, Sequence[str], None] = '9726c85cad42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('board_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labels_board_id'), 'labels', ['board_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('board_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('list_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('urgent', 'high', 'normal', 'low', name='priority'), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severity'), nullable=True),
    sa.Column('source', sa.Enum('internal', 'client', name='cardsource'), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_board_id'), 'cards', ['board_id'], unique=False)
    op.create_index(op.f('ix_cards_created_by_id'), 'cards', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_cards_list_id'), 'cards', ['list_id'], unique=False)
    op.create_table('card_assignees',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('card_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'user_id', name='uq_card_assignee')
    )
    op.create_index(op.f('ix_card_assignees_card_id'), 'card_assignees', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_assignees_user_id'), 'card_assignees', ['user_id'], unique=False)
    op.create_table('card_labels',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('card_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('label_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'label_id', name='uq_card_label')
    )
    op.create_index(op.f('ix_card_labels_card_id'), 'card_labels', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_labels_label_id'), 'card_labels', ['label_id'], unique=False)
    op.create_table('card_meta',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('card_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('viewport', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_meta_card_id'), 'card_meta', ['card_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_meta_card_id'), table_name='card_meta')
    op.drop_table('card_meta')
    op.drop_index(op.f('ix_card_labels_label_id'), table_name='card_labels')
    op.drop_index(op.f('ix_card_labels_card_id'), table_name='card_labels')
    op.drop_table('card_labels')
    op.drop_index(op.f('ix_card_assignees_user_id'), table_name='card_assignees')
    op.drop_index(op.f('ix_card_assignees_card_id'), table_name='card_assignees')
    op.drop_table('card_assignees')
    op.drop_index(op.f('ix_cards_list_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_created_by_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_board_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_labels_board_id'), table_name='labels')
    op.drop_table('labels')
    # ### end Alembic commands ###
